# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_text_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogTextEdit(object):
    def setupUi(self, DialogTextEdit):
        DialogTextEdit.setObjectName("DialogTextEdit")
        DialogTextEdit.resize(500, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DialogTextEdit)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit_content = QtWidgets.QPlainTextEdit(DialogTextEdit)
        self.plainTextEdit_content.setFrameShape(QtWidgets.QFrame.Box)
        self.plainTextEdit_content.setObjectName("plainTextEdit_content")
        self.verticalLayout.addWidget(self.plainTextEdit_content)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_confirm = QtWidgets.QPushButton(DialogTextEdit)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_confirm.setFont(font)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.horizontalLayout.addWidget(self.pushButton_confirm)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_cancel = QtWidgets.QPushButton(DialogTextEdit)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(DialogTextEdit)
        QtCore.QMetaObject.connectSlotsByName(DialogTextEdit)

    def retranslateUi(self, DialogTextEdit):
        _translate = QtCore.QCoreApplication.translate
        DialogTextEdit.setWindowTitle(_translate("DialogTextEdit", "编辑窗口"))
        self.pushButton_confirm.setText(_translate("DialogTextEdit", "确认"))
        self.pushButton_cancel.setText(_translate("DialogTextEdit", "取消"))
