[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.0.0",
    "pyperclip>=1.9.0",
    "pyqt5>=5.15.11",
]

[tool.uv]
constraint-dependencies = ["pyqt5-qt5 <=5.15.2"]
